# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 997e04124d96db88e6ab76baf45dd78664a5235142d183cbc211bdd577b59e9a48748c669fd3a571da7b2206d99a1342f715e29401c23c1ac1a6aa56a7a01bc3

test:
  secret_key_base: 600d8b697923fadf47f01557f16f289018b10984b0da4be0942ceff2113ba860d2eae122a1aa7bc20599fb7571172d7da619bfd0b707b4dca1341bf6d29cc0ed

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
